// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	ID                  int         `json:"Id"`
	BadgeNumber         int         `json:"BadgeNumber"`
	FirstName           string      `json:"FirstName"`
	LastName            string      `json:"LastName"`
	VacationAccrualRate float64     `json:"VacationAccrualRate"`
	VacationAccrued     float64     `json:"VacationAccrued"`
	Vacations           []*Vacation `json:"Vacations"`
}

type EmployeeInput struct {
	ID                  int     `json:"Id"`
	BadgeNumber         int     `json:"BadgeNumber"`
	FirstName           string  `json:"FirstName"`
	LastName            string  `json:"LastName"`
	VacationAccrualRate float64 `json:"VacationAccrualRate"`
}

type Vacation struct {
	ID          int     `json:"Id"`
	StartDate   int     `json:"StartDate"`
	Duration    float64 `json:"Duration"`
	IsCancelled bool    `json:"IsCancelled"`
}
